# version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - WEBHOOK_URL=https://${N8N_HOST}/
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_PROXY_HOPS=1
      - N8N_SECURE_COOKIE=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - TELEGRAM_USER_CHAT_ID=${TELEGRAM_USER_CHAT_ID}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - trading_net

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "n8n:5678"
      - "--domain=${N8N_HOST}"
    depends_on:
      - n8n
    networks:
      - trading_net

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - trading_net

  telethon:
    build: ./telethon-service
    restart: always
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/kronos-telethon-signal
    volumes:
      - telethon_session:/app/session
    depends_on:
      - n8n
    networks:
      - trading_net

volumes:
  n8n_data:
  telethon_session:
  postgres_data:

networks:
  trading_net:
    driver: bridge